DROP TABLE IF EXISTS `o_loans`;

CREATE TABLE `o_loans` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `loan_code` varchar(30) DEFAULT NULL COMMENT 'Custom loan code',
  `customer_id` int NOT NULL,
  `group_id` int DEFAULT '0',
  `asset_id` int NOT NULL DEFAULT '0',
  `account_number` varchar(30) NOT NULL COMMENT 'E.g. mobile, bank',
  `product_id` int NOT NULL,
  `loan_type` int NOT NULL DEFAULT '0',
  `loan_amount` double(50,2) NOT NULL,
  `disbursed_amount` double(50,2) NOT NULL,
  `total_repayable_amount` double(50,2) NOT NULL,
  `total_repaid` double(50,2) NOT NULL,
  `loan_balance` double(50,2) NOT NULL,
  `period` int NOT NULL,
  `period_units` varchar(30) NOT NULL,
  `payment_frequency` varchar(30) NOT NULL,
  `payment_breakdown` varchar(75) NOT NULL,
  `total_addons` double(50,2) NOT NULL,
  `total_deductions` double(50,2) NOT NULL,
  `total_instalments` int NOT NULL COMMENT 'Total installments in this loan',
  `total_instalments_paid` int NOT NULL COMMENT 'How many instalments have been paid',
  `current_instalment` int NOT NULL COMMENT 'We are in instalment number?',
  `current_instalment_amount` double(50,2) DEFAULT NULL,
  `income_earned` double(50,2) DEFAULT '0.00',
  `given_date` date NOT NULL,
  `next_due_date` date NOT NULL,
  `final_due_date` date NOT NULL,
  `added_by` int NOT NULL,
  `current_agent` int NOT NULL,
  `current_lo` int DEFAULT NULL,
  `current_co` int DEFAULT NULL,
  `allocation` varchar(10) DEFAULT 'BRANCH',
  `current_branch` int NOT NULL,
  `added_date` datetime NOT NULL,
  `loan_stage` int NOT NULL,
  `loan_flag` int NOT NULL COMMENT 'from o_flags',
  `transaction_code` varchar(40) NOT NULL,
  `transaction_date` datetime NOT NULL,
  `application_mode` varchar(40) NOT NULL COMMENT 'MANUAL, APP, USSD, SMS',
  `disburse_state` varchar(45) DEFAULT 'NONE' COMMENT 'NONE, INITIATED, DELIVERED, FAILED, REVERSED',
  `disbursed` int DEFAULT '0' COMMENT 'Whether the loan was given or not',
  `paid` int DEFAULT '0' COMMENT 'paid or not. each state encapsulates multiple statuses',
  `other_info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `status` int NOT NULL COMMENT 'From o_loan_statuses',
  PRIMARY KEY (`uid`),
  KEY `customer_id` (`customer_id`),
  KEY `asset_id` (`asset_id`),
  CONSTRAINT `o_loans_chk_1` CHECK (json_valid(`other_info`))
);