version: '3.8'

services:
  superlender-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./superlender:/var/www/html
    environment:
      - DB_HOST=mysql # Name of the MySQL service in this compose file
      - DB_USER=root
      - DB_PASSWORD=your_db_password # Replace with your actual password
      - DB_NAME=your_database_name # Replace with your actual database name
    networks:
      - superlender-network

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - superlender-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_db_password # Replace with your actual password
      MYSQL_DATABASE: your_database_name # Replace with your actual database name
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - superlender-network

networks:
  superlender-network:

volumes:
  mysql-data: