<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: access");
header("Access-Control-Allow-Methods: POST, GET, PUT");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
$data = json_decode(file_get_contents('php://input'), true);
session_start();
$_SESSION['db_name'] = 'bodafund_db';
include_once ("../configs/conn.inc");
include_once ("../php_functions/functions.php");



$consumerKey='8TAFklBTwAtVmXpUos3xmPSDALCulHMG'; ///////- Simple Pay
$consumerSecret='BWYpRMIsGTQVqGHA';          ///////- Simple Pay

$headers=['Content-Type:application/json; charset=utf8'];
$url = 'https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
$curl = curl_init($url);
curl_setopt($curl,CURLOPT_HTTPHEADER,$headers);
curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);

curl_setopt($curl,CURLOPT_HEADER,false);

curl_setopt($curl,CURLOPT_USERPWD,$consumerKey.':'.$consumerSecret);
$result = curl_exec($curl);
$status = curl_getinfo($curl,CURLINFO_HTTP_CODE);
$result = json_decode($result);
$access_token = $result->access_token;
echo 'The access token is: '.$access_token;

$url = 'https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest';//sktpush url
$BusinessShortCode='4121193';//shortcode
$Passkey='c5933bba702491e9ca5112cdd21f0b09db812294ba188207c2a2c5680a87f9ed';//passkey
$InitiatorName = 'Benard Musau';
$Timestamp='20'.date(    "ymdhis");//timestamp
$Password=base64_encode($BusinessShortCode.$Passkey.$Timestamp);//password encoded Base64



$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json', 'Authorization:Bearer '.$access_token)); //setting custom header


$curl_post_data = array(
    //Fill in the request parameters with valid values
    'BusinessShortCode' => $BusinessShortCode,//The organization shortcode used to receive the transaction.
    'InitiatorName' => $InitiatorName,//This is the credential/username used to authenticate the transaction request.
    'Password' => $Password,//This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
    'Timestamp' => $Timestamp,//The timestamp of the transaction in the format yyyymmddhhiiss.
    'TransactionType' => 'CustomerPayBillOnline',//The transaction type to be used for this request.
    'Amount' => '10',//The amount to be transacted.
    'PartyA' => '254716330450',//The MSISDN sending the funds.
    'PartyB' => $BusinessShortCode,//The organization shortcode receiving the funds
    'PhoneNumber' => '254716330450',//The MSISDN sending the funds.
    'CallBackURL' => 'https://www.superlender.co.ke/',//The url to where logs from M-Pesa will be sent to.
    'AccountReference' => 'Lender1',//Used with M-Pesa PayBills.
    'TransactionDesc' => 'Pay'//A description of the transaction.
);

$data_string = json_encode($curl_post_data);

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);

$curl_response = curl_exec($curl);
print_r($curl_response);



//display result
echo $curl_response;
