<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: access");
header("Access-Control-Allow-Methods: POST, GET, PUT");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
$data = json_decode(file_get_contents('php://input'), true);
session_start();
$_SESSION['db_name'] = 'tenakata_db';
include_once ("../configs/conn.inc");
include_once ("../php_functions/functions.php");

////------APPLY LOAN


$session_code = $data['session_id'];
$device_id = $data['device_id'];
$amount = $data['amount'];


if((input_length($device_id, 10)) == 0){
    $result_ = 0;
    $details_ = '"Invalid device Id"';
    $result_code = 102;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    die();
    exit();
}
if((input_length($session_code, 10)) == 0){
    $result_ = 0;
    $details_ = '"Invalid Session Code"';
    $result_code = 102;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    die();
    exit();
}
if($amount < 10){
    $result_ = 0;
    $details_ = '"Please enter a Valid amount"';
    $result_code = 102;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    die();
    exit();
}




$session_d = fetchonerow('o_customer_sessions',"device_id='$device_id' AND session_code='$session_code' AND ending_date >= '$fulldate' AND status=1","uid, customer_id");
if($session_d['uid'] < 1){
    $result_ = 0;
    $details_ = '"Session Invalid"';
    $result_code = 107;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    die();
    exit();
}
else{
    $cust_det = fetchonerow('o_customers',"uid=".$session_d['customer_id']."","primary_mobile");

    $phone = $cust_det['primary_mobile'];

    ////-------Initiate STK
    $consumerKey=fetchrow('o_mpesa_configs',"property_name='c2b_consumerKey' AND status=1","property_value"); ///////For STK push
    $consumerSecret=fetchrow('o_mpesa_configs',"property_name='c2b_consumerSecret' AND status=1","property_value");          ///////For STK push
    $c2b_short_code=fetchrow('o_mpesa_configs',"property_name='C2B_shortcode' AND status=1","property_value");

    $headers=['Content-Type:application/json; charset=utf8'];
    $url = 'https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
    $curl = curl_init($url);
    curl_setopt($curl,CURLOPT_HTTPHEADER,$headers);
    curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);

    curl_setopt($curl,CURLOPT_HEADER,false);

    curl_setopt($curl,CURLOPT_USERPWD,$consumerKey.':'.$consumerSecret);
    $result = curl_exec($curl);
    $status = curl_getinfo($curl,CURLINFO_HTTP_CODE);
    $result = json_decode($result);
    $access_token = $result->access_token;
//echo 'The access token is: '.$access_token;

    $url = 'https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest';//sktpush url
    $BusinessShortCode=$c2b_short_code;//shortcode
    $Passkey= fetchrow('o_mpesa_configs',"property_name='c2b_passkey' AND status=1","property_value");//passkey
    $InitiatorName = fetchrow('o_mpesa_configs',"property_name='c2b_InitiatorName' AND status=1","property_value");;
    $Timestamp='20'.date(    "ymdhis");//timestamp
    $Password=base64_encode($BusinessShortCode.$Passkey.$Timestamp);//password encoded Base64



    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json', 'Authorization:Bearer '.$access_token)); //setting custom header


    $curl_post_data = array(
        //Fill in the request parameters with valid values
        'BusinessShortCode' => $BusinessShortCode,//The organization shortcode used to receive the transaction.
        'InitiatorName' => $InitiatorName,//This is the credential/username used to authenticate the transaction request.
        'Password' => $Password,//This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
        'Timestamp' => $Timestamp,//The timestamp of the transaction in the format yyyymmddhhiiss.
        'TransactionType' => 'CustomerPayBillOnline',//The transaction type to be used for this request.
        'Amount' => $amount,//The amount to be transacted.
        'PartyA' => $phone,//The MSISDN sending the funds.
        'PartyB' => $BusinessShortCode,//The organization shortcode receiving the funds
        'PhoneNumber' => $phone,//The MSISDN sending the funds.
        'CallBackURL' => 'https://www.superlender.co.ke/',//The url to where logs from M-Pesa will be sent to.
        'AccountReference' => $phone,//Used with M-Pesa PayBills.
        'TransactionDesc' => 'Pay'//A description of the transaction.
    );

    $data_string = json_encode($curl_post_data);

    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);

    $curl_response = curl_exec($curl);

    $json = $curl_response;
    $j = json_decode($curl_response);
    $state = $j->ResponseCode;
    $desc = $j->ResponseDescription;
    $errorMessage = $j->errorMessage;

    if ($state == '0') {

        ///----Check latest loan and store the event
        $result_ = 1;
        $details_ = "Please wait for the prompt sent to your phone";


        $latest_ = fetchmax('o_loans',"account_number='$phone'","given_date","uid");
        $latest_loan = $latest_['uid'];

        if($latest_loan > 0){
           // $event = "STK Pushed by customer to phone on [$fulldate] with result ($state) $desc";
           // store_event('o_loans', $latest_loan,"$event");
        }
    }
    else{
        $result_ = 0;
        $details_ = "Unable to send request";

    }





        $result_code = 111;
        echo json_encode("{\"result_\":$result_,\"details_\":\"$details_\", \"result_code\":$result_code}");

}



