<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: access");
header("Access-Control-Allow-Methods: POST, GET, PUT");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
$data = json_decode(file_get_contents('php://input'), true);
session_start();
$_SESSION['db_name'] = 'bodafund_db';
include_once ("../configs/conn.inc");
include_once ("../php_functions/functions.php");

////------APPLY LOAN

$session_code = $data['session_id'];
$device_id = $data['device_id'];

$amount = floor($data['amount']);
$ref = $data['ref'];


if((input_length($device_id, 10)) == 0){
    $result_ = 0;
    $details_ = '"Invalid device Id"';
    $result_code = 102;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    store_event('o_customers', 0,"$result_, $details_, $result_code");
    die();
    exit();
}
if((input_length($session_code, 10)) == 0){
    $result_ = 0;
    $details_ = '"Invalid Session Code"';
    $result_code = 102;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    store_event('o_customers', 0,"$result_, $details_, $result_code");
    die();
    exit();
}



$session_d = fetchonerow('o_customer_sessions',"device_id='$device_id' AND session_code='$session_code' AND ending_date >= '$fulldate' AND status=1","uid, customer_id");
if($session_d['uid'] < 1){
    $result_ = 0;
    $details_ = '"Session Invalid"';
    $result_code = 107;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    store_event('o_customers', 0,"$result_, $details_, $result_code");
    die();
    exit();
}
else {
    $cust_det = fetchonerow('o_customers', "uid=" . $session_d['customer_id'] . "", "primary_product, loan_limit, status, primary_mobile, branch, national_id");
    $primary_product = $cust_det['primary_product'];
    $loan_limit = $cust_det['loan_limit'];
    $status = $cust_det['status'];
    $cust_id = $session_d['customer_id'];
    $primary_mobile = $cust_det['primary_mobile'];
    $cust_branch = $cust_det['branch'];
    $national_id = $cust_det['national_id'];
}


//Authenticate your app

$consumerKey='8TAFklBTwAtVmXpUos3xmPSDALCulHMG'; ///////- Simple Pay
$consumerSecret='BWYpRMIsGTQVqGHA';          ///////- Simple Pay

$headers=['Content-Type:application/json; charset=utf8'];
$url = 'https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
$curl = curl_init($url);
curl_setopt($curl,CURLOPT_HTTPHEADER,$headers);
curl_setopt($curl,CURLOPT_RETURNTRANSFER,true);

curl_setopt($curl,CURLOPT_HEADER,false);

curl_setopt($curl,CURLOPT_USERPWD,$consumerKey.':'.$consumerSecret);
$result = curl_exec($curl);
$status = curl_getinfo($curl,CURLINFO_HTTP_CODE);
$result = json_decode($result);
$access_token = $result->access_token;
//echo 'The access token is: '.$access_token;

$url = 'https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest';//sktpush url
$BusinessShortCode='4121193';//shortcode
$Passkey='084aed59dc05711860b12ddee560af47d5513a2c35eee963fbbb08b2113beefa';//passkey
$InitiatorName = 'WILSON';
$Timestamp='20'.date(    "ymdhis");//timestamp
$Password=base64_encode($BusinessShortCode.$Passkey.$Timestamp);//password encoded Base64



$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json', 'Authorization:Bearer '.$access_token)); //setting custom header


$curl_post_data = array(
    //Fill in the request parameters with valid values
    'BusinessShortCode' => $BusinessShortCode,//The organization shortcode used to receive the transaction.
    'InitiatorName' => $InitiatorName,//This is the credential/username used to authenticate the transaction request.
    'Password' => $Password,//This is generated by base64 encoding BusinessShortcode, Passkey and Timestamp.
    'Timestamp' => $Timestamp,//The timestamp of the transaction in the format yyyymmddhhiiss.
    'TransactionType' => 'CustomerPayBillOnline',//The transaction type to be used for this request.
    'Amount' => ''.$amount.'',//The amount to be transacted.
    'PartyA' => ''.$primary_mobile.'',//The MSISDN sending the funds.
    'PartyB' => $BusinessShortCode,//The organization shortcode receiving the funds
    'PhoneNumber' => ''.$primary_mobile.'',//The MSISDN sending the funds.
    'CallBackURL' => 'https://www.superlender.co.ke/',//The url to where logs from M-Pesa will be sent to.
    'AccountReference' => ''.$ref.$national_id.'',//Used with M-Pesa PayBills.
    'TransactionDesc' => 'Pay'//A description of the transaction.
);

$data_string = json_encode($curl_post_data);

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);

curl_exec($curl);
//print_r($curl_response);

if((input_length($session_code, 10)) == 0){
    $result_ = 1;
    $details_ = '"STK Push sent"';
    $result_code = 111;
    echo json_encode("{\"result_\":$result_,\"details_\":$details_, \"result_code\":$result_code}");
    store_event('o_customers', 0,"$result_, $details_, $result_code");
    die();
    exit();
}
